export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_SUCCESS_WITH_WARNING = 'FETCH_PRODUCTS_SUCCESS_WITH_WARNING';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const ENABLE_REGISTER_USER = 'ENABLE_REGISTER_USER';
export const DISABLE_REGISTER_USER = 'DISABLE_REGISTER_USER';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_SUCCESS_WITH_WARNING = 'REGISTER_USER_SUCCESS_WITH_WARNING';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const ENABLE_LOGIN = 'ENABLE_LOGIN';
export const DISABLE_LOGIN = 'DISABLE_LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_SUCCESS_WITH_WARNING = 'LOGIN_SUCCESS_WITH_WARNING';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_SHOPPING_CART_START = 'FETCH_SHOPPING_CART_START';
export const FETCH_SHOPPING_CART_SUCCESS = 'FETCH_SHOPPING_CART_SUCCESS';
export const FETCH_SHOPPING_CART_SUCCESS_WITH_WARNING = 'FETCH_SHOPPING_CART_SUCCESS_WITH_WARNING';
export const FETCH_SHOPPING_CART_FAILURE = 'FETCH_SHOPPING_CART_FAILURE';

export const FETCH_NONUSER_SHOPPING_CART_START = 'FETCH_SHOPPING_CART_START';
export const FETCH_NONUSER_SHOPPING_CART_SUCCESS = 'FETCH_SHOPPING_CART_SUCCESS';
export const FETCH_NONUSER_SHOPPING_CART_SUCCESS_WITH_WARNING = 'FETCH_SHOPPING_CART_SUCCESS_WITH_WARNING';
export const FETCH_NONUSER_SHOPPING_CART_FAILURE = 'FETCH_SHOPPING_CART_FAILURE';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS_WITH_WARNING = 'ADD_TO_CART_SUCCESS_WITH_WARNING';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS_WITH_WARNING = 'REMOVE_FROM_CART_SUCCESS_WITH_WARNING';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const INCREASE_CART_ITEM_QUANTITY = 'INCREASE_CART_ITEM_QUANTITY';
export const DECREASE_CART_ITEM_QUANTITY = 'DECREASE_CART_ITEM_QUANTITY';

export const LOGOUT = 'LOGOUT';
